### PR TITLE
Release/mui v5 style updates

### PR DESCRIPTION
**Pull request by bkarambe**
Fixes # BLUI-3029

#### Changes proposed in this Pull Request:
- Updated templates to use sx prop
- Updated react comp dep to latest beta

#### To Test:
- Create a project using templates -
npx -p @brightlayer-ui/cli blui new react --template=authentication
- Compare project created using dev branch vs release/mui-v5-style-updates

### CODE REVIEW

**Comment by emclaug2** [comment]
I generated a new project using the authentication-typescript template and got hit with this error after running `yarn start`:
```
 Invalid module name in augmentation, module '@mui/styles/defaultTheme' cannot be found.
     6 | import { DrawerContext } from './contexts/drawerContextProvider';                     
     7 |                                                                                       
  >  8 | declare module '@mui/styles/defaultTheme' {                                           
       |                ^^^^^^^^^^^^^^^^^^^^^^^^^^                                             
     9 |     // eslint-disable-next-line                                                       
    10 |     interface DefaultTheme extends Theme {}                                           
    11 | }    
```

**Comment by daileytj** [comment]
> #### To Test:
> * Create a project using templates -
>   npx create-react-app {project-name} --template file:{template}
> * Compare project created using dev branch vs release/mui-v5-style-updates

@bkarambe Why are you suggesting we use `npx create-react-app` to test the templates? These should be tested using the brightlayer-ui CLI. We're these working for you using `create-react-app`?

**Comment by bkarambe** [comment]
> > #### To Test:
> > 
> > * Create a project using templates -
> >   npx create-react-app {project-name} --template file:{template}
> > * Compare project created using dev branch vs release/mui-v5-style-updates
> 
> @bkarambe Why are you suggesting we use `npx create-react-app` to test the templates? These should be tested using the brightlayer-ui CLI. We're these working for you using `create-react-app`?

Yes these should be tested using blui. I'm sorry I copied wrong lines from readme, while writing description. Updated the description.

**Comment by bkarambe** [comment]
> I generated a new project using the authentication-typescript template and got hit with this error after running `yarn start`:
> 
> ```
>  Invalid module name in augmentation, module '@mui/styles/defaultTheme' cannot be found.
>      6 | import { DrawerContext } from './contexts/drawerContextProvider';                     
>      7 |                                                                                       
>   >  8 | declare module '@mui/styles/defaultTheme' {                                           
>        |                ^^^^^^^^^^^^^^^^^^^^^^^^^^                                             
>      9 |     // eslint-disable-next-line                                                       
>     10 |     interface DefaultTheme extends Theme {}                                           
>     11 | }    
> ```

Strange, after running yarn start, project runs successfully. Still I removed the module declaration in App.test.tsx

**Comment by daileytj** [comment]
Can we get a package version update as well as a changelog entry to reflect these changes. You can do a beta version so that it publishes on merge.

**Review by daileytj — APPROVED** [review]

**Pull request merged**
