### PR TITLE
Update Dependencies

### LINKED ISSUE #58: Templates should use latest @types/react and @types/react-dom dependencies
#### Describe the bug
Templates don't use latest @types/react and @types/react-dom dependencies which causes a linting error on newly generated projects

#### What is the expected behavior?
Templates should use latest @types/react and @types/react-dom dependencies

#### What are the steps to reproduce?
1. Generate new react app with the cli
2. start project via 'npm start'
3. observe linting error associated with @types/react and @types/react-dom

### PR DESCRIPTION
**Pull request by emclaug2**
Fixes #58 

### Changed

-   Updated dependencies ([#58](https://github.com/brightlayer-ui/react-component-library/issues/58)).

### CODE REVIEW

**Comment by jeffvg** [comment]
seeing this when doing yarn build on auth-typescript project. Anyone else getting the same?

image

**Comment by daileytj** [comment]
@jeffvg this looks like an issue with the login-workflow package rather than the templates or cli

**Comment by daileytj** [comment]
@emclaug2 @jeffvg I logged an issue and am actively working on getting react-workflows building properly. We will need another patch to get the auth ts template building properly. This current PR will fix the TS blank and routing templates, but we'll need another patch so I'll leave it up to the group to decide whether we put this in a publish twice or wait and publish once.

**Comment by jeffvg** [comment]
> 

I vote wait for auth ts

**Comment by emclaug2** [comment]
> > 
> 
> I vote wait for auth ts

After today's standup it looks like we're leaning towards doing a double-patch approach.   @daileytj Let's fix the blank & routing templates today.

**Review by daileytj — APPROVED** [review]

**Comment by jeffvg** [comment]
I just spun up react routing TS and got this warning. any concerns?
npm WARN @mui/styles@5.6.1 requires a peer of react@^17.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by jeffvg** [comment]
Auth-ts seems to compile but at run time throwing this up...

image

**Comment by jeffvg** [comment]
running these in case someone wants to know
npx -p @brightlayer-ui/cli blui new react blankts --template=file:/users/enum/blui/react-cli-templates/blank-typescript
or
npx create-react-app blankts --template file:/users/enum/blui/react-cli-templates/blank-typescript

**Review by jeffvg — APPROVED** [review]
looks good

**Pull request merged**
